FROM node:16 as build

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update && \
	apt-get install -y \
	openssh-client \
	ca-certificates \
	yarn \
	git \
	gnupg \
	&& rm -rf /var/lib/apt/lists/*

RUN update-ca-certificates

RUN mkdir -p ~/.ssh && chmod 700 ~/.ssh
RUN ssh-keyscan github.com >> ~/.ssh/known_hosts

RUN git clone --depth 1 https://github.com/dsaul/DispatchPulse-CE -b master /source

WORKDIR /source/frontend

RUN yarn install
RUN yarn build


FROM nginx:latest

# Remove the default html.
WORKDIR /usr/share/nginx/html
RUN rm -rf * 
COPY --from=build /source/frontend/dist /usr/share/nginx/html/

# Install our own config file.
WORKDIR /etc/nginx/conf.d/
COPY docker-includes/dispatch-pulse-ce-webapp.default.conf.template.txt /default.conf.template

CMD ["/bin/sh" , "-c" , "envsubst '$API_ROOT,$NAV_PICTURE_URI' < /default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]