FROM nginx:1.21-alpine

# Add packages we need.
RUN apk --no-cache add bash git tini nano ca-certificates openssh-client elinks && update-ca-certificates
RUN mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

# Remove the default html.
WORKDIR /usr/share/nginx/html
RUN rm -rf * 

# Install our own config file.
WORKDIR /etc/nginx
COPY docker-includes/proxy.nginx.conf nginx.conf

WORKDIR /etc/nginx/conf.d/
COPY docker-includes/proxy.default.conf default.conf
COPY docker-includes/proxy.site-backend.conf site-backend.conf
COPY docker-includes/proxy.site-frontend.conf site-frontend.conf

WORKDIR /etc/nginx/
COPY docker-includes/proxy.self-signed-backend.crt /etc/nginx/self-signed-backend.crt
COPY docker-includes/proxy.self-signed-backend.key /etc/nginx/self-signed-backend.key
COPY docker-includes/proxy.self-signed-frontend.crt /etc/nginx/self-signed-frontend.crt
COPY docker-includes/proxy.self-signed-frontend.key /etc/nginx/self-signed-frontend.key

# Install our own scripts to manage this container.
WORKDIR /
COPY docker-includes/proxy.entry.sh /entry.sh

RUN chmod a+x /entry.sh
RUN chmod a+r /entry.sh

ENTRYPOINT ["/sbin/tini", "--", "/entry.sh"]
CMD ["bash"]