
FROM debian:bullseye

# Add packages we need.
RUN apt-get update && apt-get install -y \
	tini \
	asterisk \
	sngrep \
	nano \
	gettext \
	iputils-ping \
	&& rm -rf /var/lib/apt/lists/*


RUN rm -rv /etc/asterisk/*
COPY docker-includes/dispatch-pulse-ce-callcontrol-projects-scheduling-time.asterisk/ /etc/asterisk/

COPY docker-includes/dispatch-pulse-ce-callcontrol-projects-scheduling-time.entry.sh /entry.sh
RUN chmod +x /entry.sh
COPY docker-includes/dispatch-pulse-ce-callcontrol-projects-scheduling-time.script.sh /script.sh
RUN chmod +x /script.sh

ENTRYPOINT ["/usr/bin/tini", "--", "/entry.sh"]
CMD ["bash"]

