//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedCode.Databases.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedCode.Databases.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO public.&quot;billing-journal-entries-type&quot; VALUES (&apos;b2c51cd2-4e91-11e9-b8eb-02420a000033&apos;, &apos;Basic&apos;, &apos;{}&apos;);
        ///INSERT INTO public.&quot;billing-journal-entries-type&quot; VALUES (&apos;b2cbd66c-4e91-11e9-b8eb-02420a000033&apos;, &apos;Reverse Previous Entry&apos;, &apos;{}&apos;);
        ///INSERT INTO public.&quot;billing-journal-entries-type&quot; VALUES (&apos;c8345de4-4e91-11e9-b8eb-02420a000033&apos;, &apos;Promotional Discount&apos;, &apos;{}&apos;);
        ///INSERT INTO public.&quot;billing-journal-entries-type&quot; VALUES (&apos;c83b9456-4e91-11e9-b8eb-02420a000033&apos;, &apos;Account Credit&apos;, &apos;{}&apos;);
        ///INSERT INTO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLInsertDefaultBillingJournalEntriesType {
            get {
                return ResourceManager.GetString("SQLInsertDefaultBillingJournalEntriesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO public.&quot;billing-packages-type&quot; VALUES (&apos;9a8c727e-49d1-11e9-a9f2-02420a000033&apos;, &apos;Primary&apos;, &apos;{}&apos;);
        ///INSERT INTO public.&quot;billing-packages-type&quot; VALUES (&apos;9a928934-49d1-11e9-a9f2-02420a000033&apos;, &apos;Add-on&apos;, &apos;{}&apos;);.
        /// </summary>
        internal static string SQLInsertDefaultBillingPackagesType {
            get {
                return ResourceManager.GetString("SQLInsertDefaultBillingPackagesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO public.&quot;billing-permissions-bool&quot; VALUES (&apos;292adec6-133e-11eb-83c3-02420a000092&apos;, &apos;crm.employment-status.request-any&apos;, true, NULL, &apos;456f60fe-774c-11ea-9784-02420a0000d8&apos;, &apos;{}        ///
        ///&apos;);
        ///INSERT INTO public.&quot;billing-permissions-bool&quot; VALUES (&apos;ad484844-7751-11ea-8ada-02420a0000d8&apos;, &apos;billing.contacts.modify-company&apos;, true, NULL, &apos;4579df84-774c-11ea-9784-02420a0000d8&apos;, &apos;{}        ///
        ///&apos;);
        ///INSERT INTO public.&quot;billing-permissions-bool&quot; VALUES (&apos;ad4d1cd4-7751-11ea-8ada-02420a0000d8&apos;, &apos;billing.contacts.delete-company [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLInsertDefaultBillingPermissionsBool {
            get {
                return ResourceManager.GetString("SQLInsertDefaultBillingPermissionsBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO public.&quot;billing-permissions-groups&quot; VALUES (&apos;456f60fe-774c-11ea-9784-02420a0000d8&apos;, &apos;Base: Super Admin&apos;, &apos;{ &quot;hidden&quot;: true }&apos;);
        ///INSERT INTO public.&quot;billing-permissions-groups&quot; VALUES (&apos;458369a0-774c-11ea-9784-02420a0000d8&apos;, &apos;Base: Employee (Tier 1, Minimum)&apos;, &apos;{ &quot;hidden&quot;: false }&apos;);
        ///INSERT INTO public.&quot;billing-permissions-groups&quot; VALUES (&apos;457eac94-774c-11ea-9784-02420a0000d8&apos;, &apos;Base: Supervisor (Tier 2)&apos;, &apos;{ &quot;hidden&quot;: false }        ///
        ///&apos;);
        ///INSERT INTO public.&quot;billing-permissions-groups&quot; VALUES (&apos;4579 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLInsertDefaultBillingPermissionsGroups {
            get {
                return ResourceManager.GetString("SQLInsertDefaultBillingPermissionsGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO public.&quot;billing-payment-frequencies&quot; VALUES (&apos;905ee50e-3efd-11e9-b372-02420a000011&apos;, &apos;Quarterly&apos;, &apos;Quarterly&apos;, 3, &apos;{}&apos;);
        ///INSERT INTO public.&quot;billing-payment-frequencies&quot; VALUES (&apos;9064e468-3efd-11e9-b372-02420a000011&apos;, &apos;Monthly&apos;, &apos;Monthly&apos;, 1, &apos;{}&apos;);
        ///INSERT INTO public.&quot;billing-payment-frequencies&quot; VALUES (&apos;9058352e-3efd-11e9-b372-02420a000011&apos;, &apos;Annually&apos;, &apos;Annually&apos;, 12, &apos;{}&apos;);.
        /// </summary>
        internal static string SQLInsertDefaultPaymentFrequencies {
            get {
                return ResourceManager.GetString("SQLInsertDefaultPaymentFrequencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO public.&quot;billing-payment-method&quot; VALUES (&apos;Invoice&apos;, &apos;55f19cf6-2d6c-11e9-87ab-02420a000cae&apos;, &apos;{}&apos;);
        ///INSERT INTO public.&quot;billing-payment-method&quot; VALUES (&apos;Square Pre-Authorized&apos;, &apos;189a8058-898f-11eb-8c22-02420a0000bb&apos;, &apos;{}&apos;);.
        /// </summary>
        internal static string SQLInsertDefaultPaymentMethod {
            get {
                return ResourceManager.GetString("SQLInsertDefaultPaymentMethod", resourceCulture);
            }
        }
    }
}
