//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARI_OnCall.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARI_OnCall.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///	&lt;style&gt;
        ///		body {
        ///			font-family: &apos;Segoe UI&apos;, Tahoma, Geneva, Verdana, sans-serif;
        ///		}
        ///
        ///		main {
        ///			border: 2px solid rgb(50, 50, 66);
        ///			max-width: 500px;
        ///			margin: 10px;
        ///			margin-left: auto;
        ///			margin-right: auto;
        ///			background: white;
        ///		}
        ///
        ///		header {
        ///			background: rgb(116, 115, 137);
        ///			color: white;
        ///			font-weight: bold;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MarkedHandledNotificationEmailTemplate {
            get {
                return ResourceManager.GetString("MarkedHandledNotificationEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///	&lt;style&gt;
        ///		body {
        ///			font-family: &apos;Segoe UI&apos;, Tahoma, Geneva, Verdana, sans-serif;
        ///		}
        ///
        ///		main {
        ///			border: 2px solid rgb(50, 50, 66);
        ///			max-width: 500px;
        ///			margin: 10px;
        ///			margin-left: auto;
        ///			margin-right: auto;
        ///			background: white;
        ///		}
        ///
        ///		header {
        ///			background: rgb(116, 115, 137);
        ///			color: white;
        ///			font-weight: bold;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewOnCallVoicemailNotificationEmailTemplate {
            get {
                return ResourceManager.GetString("NewOnCallVoicemailNotificationEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///	&lt;style&gt;
        ///		body {
        ///			font-family: &apos;Segoe UI&apos;, Tahoma, Geneva, Verdana, sans-serif;
        ///		}
        ///
        ///		main {
        ///			border: 2px solid rgb(50, 50, 66);
        ///			max-width: 500px;
        ///			margin: 10px;
        ///			margin-left: auto;
        ///			margin-right: auto;
        ///			background: white;
        ///		}
        ///
        ///		header {
        ///			background: rgb(116, 115, 137);
        ///			color: white;
        ///			font-weight: bold;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoAgentResponseNotificationEmailTemplate {
            get {
                return ResourceManager.GetString("NoAgentResponseNotificationEmailTemplate", resourceCulture);
            }
        }
    }
}
