version: "3.2"
services:
  postgres: 
    image: postgres:11
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
    networks:
      - backend
    restart: "unless-stopped"
#    ports:
#      - "32123:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CHANGEME

networks:
  frontend:
  backend:






